name: Generate Docs

on:
  push:
    branches: main

jobs:
  doc:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'
    - name: Install pnpm & deps
      uses: pnpm/action-setup@v4
      with:
        version: latest
        run_install: true
    - name: Generate Docs
      run: |
        pnpm compile && pnpm docgen
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
